
#INSERTAMOS REGISTROS EN COMUNAS

INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES (0,'Santiago');
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES (0,'Cerrillos',);
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES(0,'Pudahuel');
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES(0,'Maipú');

##INSERTAMOS ROLES

INSERT INTO ROLES(NOMBRE) VALUES('Usuario');
INSERT INTO ROLES(NOMBRE) VALUES('Ejecutivo');
INSERT INTO ROLES(NOMBRE) VALUES('Administrador');

#INSERTAMOS ESTADO

INSERT INTO ESTADO (NOMBRE) VALUES('Habilitado');
INSERT INTO ESTADO (NOMBRE) VALUES('Deshabilitado');
